# code to create the json prediction:
webApi = 'https://awsagunva1011.jnj.com:8443/WebAPI'

populationSettings <- list(PatientLevelPrediction::createStudyPopulationSettings(riskWindowEnd = 30,
                                                                                 riskWindowStart = 1,
                                                                                 washoutPeriod = 365,
                                                                                 removeSubjectsWithPriorOutcome = TRUE,
                                                                                 firstExposureOnly = TRUE,
                                                                                 priorOutcomeLookback = 99999,
                                                                                 requireTimeAtRisk = FALSE),
                           PatientLevelPrediction::createStudyPopulationSettings(riskWindowEnd = 60,
                                                                                 riskWindowStart = 1,
                                                                                 washoutPeriod = 365,
                                                                                 removeSubjectsWithPriorOutcome = TRUE,
                                                                                 firstExposureOnly = TRUE,
                                                                                 priorOutcomeLookback = 99999,
                                                                                 requireTimeAtRisk = FALSE),
                           PatientLevelPrediction::createStudyPopulationSettings(riskWindowEnd = 90,
                                                                                 riskWindowStart = 1,
                                                                                 washoutPeriod = 365,
                                                                                 removeSubjectsWithPriorOutcome = TRUE,
                                                                                 firstExposureOnly = TRUE,
                                                                                 priorOutcomeLookback = 99999,
                                                                                 requireTimeAtRisk = FALSE))


modelList <- list(list("LassoLogisticRegressionSettings" = list("variance" = 0.01)))

covariateSettings <- list(list(list(fnct = 'createCovariateSettings',
                                    settings = FeatureExtraction::createCovariateSettings(useDemographicsGender = T,
                                                                                          useDemographicsAge = T)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Autoimmune_disease',
                                                    covariateId = 22590,
                                                    cohortId = 22590,
                                                    startDay=-99999,
                                                    endDay=0,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Atrial_fibrillation',
                                                    covariateId = 22591,
                                                    cohortId = 22591,
                                                    startDay=-99999,
                                                    endDay=0,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Asthma',
                                                    covariateId = 22592,
                                                    cohortId = 22592,
                                                    startDay=-99999,
                                                    endDay=0,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Thrombophilia',
                                                    covariateId = 22593,
                                                    cohortId = 22593,
                                                    startDay=-99999,
                                                    endDay=0,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Antiphospholipid_syndrome',
                                                    covariateId = 22594,
                                                    cohortId = 22594,
                                                    startDay=-99999,
                                                    endDay=0,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Malignant_neoplastic_disease',
                                                    covariateId = 22614,
                                                    cohortId = 22614,
                                                    startDay=-99999,
                                                    endDay=0,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Diabetes_mellitus',
                                                    covariateId = 22613,
                                                    cohortId = 22613,
                                                    startDay=-99999,
                                                    endDay=0,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Obesity',
                                                    covariateId = 22612,
                                                    cohortId = 22612,
                                                    startDay=-99999,
                                                    endDay=0,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Heart_disease',
                                                    covariateId = 22611,
                                                    cohortId = 22611,
                                                    startDay=-99999,
                                                    endDay=0,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Hypertensive_disorder',
                                                    covariateId = 22618,
                                                    cohortId = 22618,
                                                    startDay=-99999,
                                                    endDay=0,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Renal_impairment',
                                                    covariateId = 22617,
                                                    cohortId = 22617,
                                                    startDay=-99999,
                                                    endDay=0,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Chronic_obstructive_lung_disease',
                                                    covariateId = 22616,
                                                    cohortId = 22616,
                                                    startDay=-99999,
                                                    endDay=0,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Dementia',
                                                    covariateId = 22615,
                                                    cohortId = 22615,
                                                    startDay=-99999,
                                                    endDay=0,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Antiinflammatory',
                                                    covariateId = 22606,
                                                    cohortId = 22606,
                                                    startDay=-183,
                                                    endDay=-4,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Coxib',
                                                    covariateId = 22605,
                                                    cohortId = 22605,
                                                    startDay=-183,
                                                    endDay=-4,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Corticosteroids',
                                                    covariateId = 22604,
                                                    cohortId = 22604,
                                                    startDay=-183,
                                                    endDay=-4,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Antithrombotic_agent',
                                                    covariateId = 22603,
                                                    cohortId = 22603,
                                                    startDay=-183,
                                                    endDay=-4,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Lipid_modifying_agent',
                                                    covariateId = 22610,
                                                    cohortId = 22610,
                                                    startDay=-183,
                                                    endDay=-4,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Antineoplastic_immunomodulating',
                                                    covariateId = 22609,
                                                    cohortId = 22609,
                                                    startDay=-183,
                                                    endDay=-4,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Hormonal_contraceptives',
                                                    covariateId = 22608,
                                                    cohortId = 22608,
                                                    startDay=-183,
                                                    endDay=-4,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Tamoxifen',
                                                    covariateId = 22607,
                                                    cohortId = 22607,
                                                    startDay=-183,
                                                    endDay=-4,
                                                    count=F, 
                                                    ageInteraction = F)),
                               list(fnct = 'createCohortCovariateSettings', 
                                    settings = list(covariateName = 'Sex_hormones_modulators',
                                                    covariateId = 22598,
                                                    cohortId = 22598,
                                                    startDay=-183,
                                                    endDay=-4,
                                                    count=F, 
                                                    ageInteraction = F)))
)

resrictOutcomePops <- NULL
resrictModelCovs <- NULL

executionSettings <- list(minCovariateFraction = 0.000,
                          normalizeData = T,
                          testSplit = "stratified",
                          testFraction = 0.20,
                          splitSeed = 1000,
                          nfold = 3)

json <- createDevelopmentStudyJson(packageName = 'CovCoagEmaPrediction',
                           packageDescription = 'Prediction model based on predictors proposed by the EMA',
                           createdBy = 'Henrik John',
                           organizationName = 'Erasmus University Medical Center',
                           targets = data.frame(targetId = c(22932),
                                                cohortId = c(22932),
                                                targetName = c('COVID19 PCR positive test or diagnosis')),
                           outcomes = data.frame(outcomeId = c(22601,22600,22599,22595,22596,22602,22933),
                                                 cohortId = c(22601,22600, 22599,22595,22596,22602,22933),
                                                 outcomeName = c('MI','IS','MI_and_IS','PE','DVT_narrow',
                                                                 'VTE_narrow', 'DTH')),
                           populationSettings = populationSettings,
                           modelList = modelList,
                           covariateSettings = covariateSettings,
                           resrictOutcomePops = resrictOutcomePops,
                           resrictModelCovs = resrictModelCovs,
                           executionSettings = executionSettings,
                           webApi = webApi,
                           outputLocation = 'D:/hjohn/CovCoagEma',
                           jsonName = 'predictionAnalysisList.json')

specifications <- Hydra::loadSpecifications(file.path('D:/hjohn/CovCoagEma', 'predictionAnalysisList.json'))
Hydra::hydrate(specifications = specifications, outputFolder = 'D:/hjohn/CovCoagEma/CovCoagEmaPrediction')
